//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp2
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PolyclinicEntities : DbContext
    {
        public PolyclinicEntities()
            : base("name=PolyclinicEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
        public static PolyclinicEntities _context;
        public static PolyclinicEntities GetContext()
        {
            if (_context == null)
            {
                _context = new PolyclinicEntities();
            }
            return _context;
        }
    
        public virtual DbSet<Cabinet> Cabinets { get; set; }
        public virtual DbSet<Doctor> Doctors { get; set; }
        public virtual DbSet<Patient> Patients { get; set; }
        public virtual DbSet<Purchase> Purchases { get; set; }
        public virtual DbSet<Report> Reports { get; set; }
        public virtual DbSet<Sale> Sales { get; set; }
        public virtual DbSet<Specialization> Specializations { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<TimeTable> TimeTables { get; set; }
        public virtual DbSet<Visit> Visits { get; set; }
        public virtual DbSet<Warehouse> Warehouses { get; set; }
        public virtual DbSet<Auth> Auths { get; set; }
    }
}
