//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Report
    {
        public int ReportID { get; set; }
        public int VisitID { get; set; }
        public Nullable<int> SaleID { get; set; }
        public Nullable<int> PurchaseID { get; set; }
    
        public virtual Purchase Purchase { get; set; }
        public virtual Sale Sale { get; set; }
        public virtual Visit Visit { get; set; }
    }
}
