//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Complect
    {
        public int ComplectId { get; set; }
        public int MainGoodId { get; set; }
        public int SecondGoodId { get; set; }
    
        public virtual Good Good { get; set; }
        public virtual Good Good1 { get; set; }
    }
}
