//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GBEntities : DbContext
    {
        public GBEntities()
            : base("name=GBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
        public static GBEntities _context;
        public static GBEntities GetContext()
        {
            if (_context == null)
            {
                _context = new GBEntities();
            }
            return _context;
        }
    
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<Client> Clients { get; set; }
        public virtual DbSet<ClientType> ClientTypes { get; set; }
        public virtual DbSet<Complect> Complects { get; set; }
        public virtual DbSet<Developer> Developers { get; set; }
        public virtual DbSet<Good> Goods { get; set; }
        public virtual DbSet<Season> Seasons { get; set; }
        public virtual DbSet<SeasonGood> SeasonGoods { get; set; }
        public virtual DbSet<Sell> Sells { get; set; }
        public virtual DbSet<SellVisit> SellVisits { get; set; }
        public virtual DbSet<Service> Services { get; set; }
        public virtual DbSet<ServiceShare> ServiceShares { get; set; }
        public virtual DbSet<Share> Shares { get; set; }
        public virtual DbSet<Speciality> Specialities { get; set; }
        public virtual DbSet<Store> Stores { get; set; }
        public virtual DbSet<TimeSheet> TimeSheets { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Visit> Visits { get; set; }
        public virtual DbSet<Worker> Workers { get; set; }
    }
}
