//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class SeasonGood
    {
        public int SeasonGoodId { get; set; }
        public int SeasonId { get; set; }
        public int GoodId { get; set; }
    
        public virtual Good Good { get; set; }
        public virtual Season Season { get; set; }
    }
}
