//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class SellVisit
    {
        public int SellVisitId { get; set; }
        public int SellId { get; set; }
        public int VisitId { get; set; }
    
        public virtual Sell Sell { get; set; }
        public virtual Visit Visit { get; set; }
    }
}
